services:
  astro:
    build:
      context: ./astro
      dockerfile: Dockerfile
    expose:
      - "3000"
    restart: unless-stopped

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - DB_HOST=db
      - DB_USER=moodle
      - DB_PASS=moodle_pass
      - DB_NAME=moodle
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy  # ✅ Espera a que la DB esté lista
    restart: unless-stopped

  moodle:
    image: bitnami/moodle:4.3.3  # ✅ Versión más estable anterior
    environment:
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodle_pass
      - MOODLE_DATABASE_NAME=moodle
      - ALLOW_EMPTY_PASSWORD=no
      - MOODLE_SKIP_BOOTSTRAP=false
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin123
      - MOODLE_EMAIL=admin@example.com
      - MOODLE_SITE_NAME=Moodle Site
      - MOODLE_EXTRA_CONFIG_FILE=/bitnami/moodle/conf/moodle_settings.php

    volumes:
      - moodle_data:/bitnami/moodle
      - ./moodle-extra-config/moodle_settings.php:/bitnami/moodle/conf/moodle_settings.php:ro
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: bitnami/mariadb:10.11
    environment:
      - MARIADB_ROOT_PASSWORD=root_pass
      - MARIADB_USER=moodle
      - MARIADB_PASSWORD=moodle_pass
      - MARIADB_DATABASE=moodle
    volumes:
      - db_data:/bitnami/mariadb
      - ./data/mariadb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_pass"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "${HTTP_PORT:-4324}:80"
    volumes:
      - ../logs/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - astro
      - auth
      - moodle
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "${ADMIN_PORT:-4325}:8080"
    restart: unless-stopped

volumes:
  moodle_data:
  db_data:
